"""
Generates a chain-of-custody style PDF forensic report — the artifact that
makes this look like an investigator's tool rather than a classroom demo.
"""

import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm


def generate_report(
    output_path: str,
    case_id: str,
    file_name: str,
    file_hash: str,
    media_type: str,
    scores: dict,
    legal_note: str,
    exif_note: str = None,
):
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], textColor=colors.HexColor("#1a1a2e"))
    heading_style = styles["Heading2"]
    normal_style = styles["Normal"]
    mono_style = ParagraphStyle("Mono", parent=styles["Normal"], fontName="Courier", fontSize=8)

    story = []
    story.append(Paragraph("DeepShield AI — Forensic Triage Report", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        normal_style,
    ))
    story.append(Spacer(1, 16))

    # Case metadata / chain of custody
    story.append(Paragraph("Case &amp; File Metadata", heading_style))
    meta_table_data = [
        ["Case ID", case_id],
        ["File name", file_name],
        ["Media type", media_type],
        ["SHA-256 hash", file_hash],
    ]
    meta_table = Table(meta_table_data, colWidths=[4*cm, 12*cm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eeeeee")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 16))

    # Verdict
    final_score = scores.get("final_score", 0.0)
    verdict = "LIKELY AI-GENERATED / MANIPULATED" if final_score >= 0.5 else "LIKELY AUTHENTIC"
    story.append(Paragraph("Detection Result", heading_style))
    story.append(Paragraph(f"<b>Verdict:</b> {verdict}", normal_style))
    story.append(Paragraph(f"<b>Confidence:</b> {final_score*100:.1f}%", normal_style))
    story.append(Spacer(1, 10))

    # Signal breakdown table
    signal_rows = [["Signal", "Score"]]
    for key, label in [
        ("model_ensemble_score", "Pretrained classifier ensemble"),
        ("ela_score", "Error Level Analysis (compression)"),
        ("fft_noise_score", "FFT frequency-domain anomaly"),
        ("face_symmetry_score", "Facial symmetry anomaly"),
        ("mean_frame_score", "Mean per-frame score (video)"),
        ("temporal_variance", "Temporal variance (video)"),
    ]:
        if key in scores and scores[key] is not None:
            val = scores[key]
            signal_rows.append([label, f"{val*100:.1f}%" if val <= 1 else f"{val:.4f}"])

    signal_table = Table(signal_rows, colWidths=[10*cm, 6*cm])
    signal_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(signal_table)
    story.append(Spacer(1, 16))

    # EXIF note
    if exif_note:
        story.append(Paragraph("Metadata Forensics", heading_style))
        story.append(Paragraph(exif_note, normal_style))
        story.append(Spacer(1, 16))

    # Legal reference note
    story.append(Paragraph("Legal Reference (India — BNS 2023 / IT Act)", heading_style))
    for line in legal_note.split("\n"):
        if line.strip():
            story.append(Paragraph(line.replace("•", "&bull;"), normal_style))
        else:
            story.append(Spacer(1, 4))
    story.append(Spacer(1, 16))

    story.append(Paragraph(
        "This report is generated by an automated triage tool for investigative "
        "assistance. It is not a certified forensic or courtroom-admissible "
        "determination. Findings should be independently verified before "
        "formal action.",
        ParagraphStyle("Disclaimer", parent=normal_style, textColor=colors.grey, fontSize=8),
    ))

    doc.build(story)
    return output_path
